import 'package:flutter/material.dart';

abstract final class AppColors {
  static const light = ColorScheme(
    brightness: Brightness.light,
    surface: Color(0xFFFAFAF8),
    onSurface: Color(0xFF1C1B19),
    onSurfaceVariant: Color(0xFF6B6A65),
    surfaceContainer: Color(0xFFF2F1EE),
    surfaceContainerHigh: Color(0xFFE8E7E3),
    outline: Color(0xFFD4D3CE),
    outlineVariant: Color(0xFFE8E7E3),
    primary: Color(0xFF4A9E8E),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD6F0EA),
    onPrimaryContainer: Color(0xFF0D3B31),
    secondary: Color(0xFF4A6E66),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFCCEDE4),
    onSecondaryContainer: Color(0xFF062A22),
    tertiary: Color(0xFF456A80),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFC9E6FF),
    onTertiaryContainer: Color(0xFF001E31),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    surface: Color(0xFF141413),
    onSurface: Color(0xFFE8E6E0),
    onSurfaceVariant: Color(0xFF9C9B95),
    surfaceContainer: Color(0xFF1E1D1B),
    surfaceContainerHigh: Color(0xFF282725),
    outline: Color(0xFF4A4944),
    outlineVariant: Color(0xFF333230),
    primary: Color(0xFF7ECEBF),
    onPrimary: Color(0xFF003F34),
    primaryContainer: Color(0xFF1A5C4F),
    onPrimaryContainer: Color(0xFFD6F0EA),
    secondary: Color(0xFFB0D1C8),
    onSecondary: Color(0xFF1C3B33),
    secondaryContainer: Color(0xFF33524A),
    onSecondaryContainer: Color(0xFFCCEDE4),
    tertiary: Color(0xFFAACDE3),
    onTertiary: Color(0xFF103447),
    tertiaryContainer: Color(0xFF2B4D63),
    onTertiaryContainer: Color(0xFFC9E6FF),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
  );
}
